# Generated by Django 6.0 on 2026-01-25 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_otp_atamots_profile_otp_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='otp_atamots',
            new_name='otp_attempts',
        ),
    ]
